name = "videoeditor"
account_id = "72e2e322ec1c23d1c20de1f2b0cf8cb5"
main = "src/index.ts"
compatibility_date = "2025-07-01"
compatibility_flags = ["nodejs_compat"]

[[containers]]
class_name = "MyContainer"
image = "./Dockerfile"
max_instances = 3

[[durable_objects.bindings]]
name = "MY_CONTAINER"
class_name = "MyContainer"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MyContainer"]
