name = "video-editor-api"
main = "src/index.ts"
compatibility_date = "2025-06-01"

[[containers]]
class_name = "MyContainer"
image = "./Dockerfile"
max_instances = 3
sleepAfter = "10m"

[[durable_objects.bindings]]
name = "MY_CONTAINER"
class_name = "MyContainer"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["MyContainer"]
